### ISSUE TITLE
Controller Creates Entity

### ISSUE THREAD

**Issue by pwrnrd** [carlphilipp/clean-architecture-example#3]
Thank you for this great example! 

After carefully reviewing your work is was wondering why you chose to have the user controller pass an User object to the usecase? 

Example:
```
public UserWeb createUser(final UserWeb userWeb) {
	var user = userWeb.toUser();
	return UserWeb.toUserWeb(createUser.create(user));
}
```
In this code, userWeb.toUser() creates an instance of User and passes it to the usecase. However, in his book, Rober C. Martin states the following:

> Typically the data that crosses the boundaries consists of simple data structures. You can use basic structs or simple data transfer objects if you like.  .... We don't want to cheat and pass Entity objects or database rows. (p. 207)

Later he continuous and states:

> The Controller packages the data into a plain old Java object and passes this object through the InputBoundaryu to the UseCaseInteractor. The UseCaseInteractor interprets the data and uses it to control the dance of the Entitites. (p. 207)

I'm wondering whether the creation of a User instance in the controller and than passing it to the usecase is in line with what Robert C. Martin states in his book. What are your thoughts on this?

**Comment by carlphilipp** [comment]
Hello,

I think the important part here is: Do not break the dependency rule. When I create/pass the User in the controller, it does not break the rule, because the controller has access to the inner layers. 

What are the other options if you do not use a `User` here? You could do:
```
public UserWeb createUser(String email, String password, String lastName, String firstName) {
	return UserWeb.toUserWeb(createUser.create(email, password, lastName, firstName));
}
```
That's not the best signature. We can try that:
```
public UserWeb createUser(Map<String, String> user) {
	return UserWeb.toUserWeb(createUser.create(user));
}
```
But well, this is not great either IMO. It's prone to mistakes and pushes some silly validation in the usecase.
Like Uncle Bob says in the part you quote, you can `packages the data into a plain old Java object and passes this object`.
It means that you need to create another object that represents a User, a sort of DTO, and this can't live in the controller layer, because both layers need to have access to it.
At that point, you need to create another layer between the controller and the usecase (or you could just put the DTO in the usecase, but that's not great).
At the end you are going to endup with:
- A User object representing the rest interface (`UserWeb` in my example)
- A User object representing the input of the usecase (The DTO I just talked about)
- A User entity
- And probably some User object representing the DB.
It's quite a lot of representation for a simple example.

I would say that it could be probably useful for a more complex usecase, but not in my example.

**Comment by pwrnrd** [comment]
Hi Carl,

Thank you, that clears it up! Within my own application I use the DTO approach.
